### ISSUE TITLE
Unable to install from setup instructions

### ISSUE THREAD

**Issue by jameski83** [perrymanuk/hashi-homelab#2]
I could do with some help setting this up - I am not overly familiar with .envrc files and can't get make base or make deploy-base to work. Could you possibly expand on the setup instructions? I have pasted the export lines into a .envrc file and added the strings but I get the message "make: *** No rule to make target 'base'.  Stop."

Any help would be greatly appreciated, as there is not very much helpful info such as yours for Nomad setups at home.

**Comment by perrymanuk** [comment]
you want to run a `make deploy-base` to get it to work for you, and you can use an .envrc or just export the variables to your shell. The variable settings should be the same as are documented in the readme.md.
The output for `make base` not working makes sense as that target doesn't exist, but a `make deploy-base` should work fine, you can also deploy individual components with a `make deploy-grafana` for example.

Hope that helps

**Comment by jameski83** [comment]
that doesn't work unfortunately. I get the below error ;

This will deploy all jobs in this repo. Are you sure? [y/N] y
/bin/sh: 1: [: y: unexpected operator
Makefile:13: recipe for target 'deploy-base' failed
make: *** [deploy-base] Error 2

I have tried changing where it says "/workdir" to the path where I have cloned your repo but still the same error.

**Comment by perrymanuk** [comment]
That can have to do with the shell you're using I think. You can remove the following line from your make file and then it should work for you...
```@echo -n "This will deploy all jobs in this repo. Are you sure? [y/N] " && read ans && [ $${ans:-N} == y ]```

**Comment by perrymanuk** [comment]
I just pushed a large update and removed this from the makefile, you shouldn't have the issue any longer :+1:

**Comment by jameski83** [comment]
Thanks the help is appreciated. Removing the line did resolve the issue and it all works fine now.

Out of interest, did you manually write all of the nomad job files, it looks like doing it manually comparing from docker compose / run is the only way as far as I can see.

**Comment by perrymanuk** [comment]
Yeah, I did them manually, I did look at a way of generating the ones based on the linuxserver images but it ended up just being easier to write out the job files.
